# Generated by Django 4.2.6 on 2024-06-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('edu_admin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.studentdetail')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_admin.classschedule')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_admin.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.studentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSubjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.employeedetail')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_admin.classschedule')),
            ],
        ),
    ]
