# Generated by Django 4.2.6 on 2024-06-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_allaccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='employment_type',
            field=models.CharField(choices=[('T', 'Teacher'), ('A', 'Administrative Staff'), ('S', 'Other Staff'), ('D', 'Dean')], max_length=1),
        ),
    ]
