# Generated by Django 4.2.6 on 2024-04-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='parentdetail',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='parentdetail',
            name='student',
        ),
        migrations.DeleteModel(
            name='RegistrationKey',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='account_id',
        ),
        migrations.DeleteModel(
            name='EmployeeDetail',
        ),
        migrations.DeleteModel(
            name='ParentDetail',
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
