# Generated by Django 4.2.6 on 2024-04-26 05:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import register.custom_utils.custom


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_employeedetail_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(default=None, max_length=80, null=True)),
                ('last_name', models.CharField(max_length=80)),
                ('suffix', models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior'), ('II', 'The second'), ('III', 'The third'), ('IV', 'The fourth'), ('V', 'The fifth')], max_length=3, null=True)),
                ('birthday', models.DateField(validators=[register.custom_utils.custom.staff_parent_age_validator])),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must follow the format '+99999999' between 8-15 digits long.", regex='^\\+?\\d{8,15}$')])),
                ('employment_type', models.CharField(choices=[('T', 'Teacher'), ('S', 'Staff'), ('D', 'Dean')], max_length=1)),
                ('status', models.CharField(choices=[('P', 'Probationary'), ('R', 'Regular'), ('S', 'Suspended'), ('T', 'Terminated')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationKey',
            fields=[
                ('generated_key', models.CharField(max_length=19, primary_key=True, serialize=False, unique=True)),
                ('key_type', models.CharField(choices=[('STU', 'Student'), ('PAR', 'Parent'), ('EMP', 'Employee')], max_length=3)),
                ('generated_for', models.CharField(max_length=255)),
                ('key_expiry', models.DateField()),
                ('key_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_name', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(default=None, max_length=80, null=True)),
                ('suffix', models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior'), ('II', 'The second'), ('III', 'The third'), ('IV', 'The fourth'), ('V', 'The fifth')], max_length=3, null=True)),
                ('birthday', models.DateField(validators=[register.custom_utils.custom.student_age_validator])),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must follow the format '+99999999' between 8-15 digits long.", regex='^\\+?\\d{8,15}$')])),
                ('status', models.CharField(choices=[('N', 'New account, not yet activated'), ('A', 'Active'), ('E', 'Expelled'), ('S', 'Suspended'), ('D', 'Dropped out'), ('G', 'Graduated'), ('X', 'Did not enroll this year')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ParentDetail',
            fields=[
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(default=None, max_length=80, null=True)),
                ('last_name', models.CharField(max_length=80)),
                ('suffix', models.CharField(choices=[('JR', 'Junior'), ('SR', 'Senior'), ('II', 'The second'), ('III', 'The third'), ('IV', 'The fourth'), ('V', 'The fifth')], max_length=3, null=True)),
                ('birthday', models.DateField(validators=[register.custom_utils.custom.staff_parent_age_validator])),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must follow the format '+99999999' between 8-15 digits long.", regex='^\\+?\\d{8,15}$')])),
                ('relationship', models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Sibling'), ('R', 'Relative'), ('G', 'Legal Guardian')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.studentdetail')),
            ],
        ),
    ]
