# Generated by Django 4.2.6 on 2024-03-17 05:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllAccountId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_id", models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.BinaryField(max_length=255)),
                ("allow_login", models.BooleanField(default=True)),
                (
                    "employee_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="register.allaccountid",
                        to_field="generated_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.BinaryField(max_length=255)),
                ("allow_login", models.BooleanField(default=True)),
                (
                    "parent_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="register.allaccountid",
                        to_field="generated_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_key", models.CharField(max_length=19, unique=True)),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("STU", "Student"),
                            ("PAR", "Parent"),
                            ("EMP", "Employee"),
                        ],
                        max_length=3,
                    ),
                ),
                ("generated_for", models.CharField(max_length=255)),
                ("key_expiry", models.DateField()),
                ("key_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.BinaryField(max_length=255)),
                ("allow_login", models.BooleanField(default=True)),
                (
                    "student_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="register.allaccountid",
                        to_field="generated_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("middle_name", models.CharField(max_length=80, null=True)),
                ("last_name", models.CharField(max_length=80)),
                (
                    "suffix",
                    models.CharField(
                        choices=[
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("II", "The second"),
                            ("III", "The third"),
                            ("IV", "The fourth"),
                            ("V", "The fifth"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("birthday", models.DateField()),
                ("address", models.CharField(max_length=255)),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must follow the format '+99999999' between 8-15 digits long.",
                                regex="^\\+?\\1?\\d{8,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Active"),
                            ("N", "New account, not yet activated"),
                            ("E", "Expelled"),
                            ("S", "Suspended"),
                            ("D", "Dropped out"),
                            ("G", "Graduated"),
                            ("X", "Did not enroll this year"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "scholar_type",
                    models.CharField(
                        choices=[
                            ("N", "Not a scholar"),
                            ("H", "Half scholarship"),
                            ("F", "Full scholarship"),
                        ],
                        max_length=1,
                    ),
                ),
                ("violations", models.BooleanField(default=False)),
                (
                    "student_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="register.studentaccount",
                        to_field="student_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("middle_name", models.CharField(max_length=80, null=True)),
                ("last_name", models.CharField(max_length=80)),
                (
                    "suffix",
                    models.CharField(
                        choices=[
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("II", "The second"),
                            ("III", "The third"),
                            ("IV", "The fourth"),
                            ("V", "The fifth"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("birthday", models.DateField()),
                ("address", models.CharField(max_length=255)),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must follow the format '+99999999' between 8-15 digits long.",
                                regex="^\\+?\\1?\\d{8,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("F", "Father"),
                            ("M", "Mother"),
                            ("S", "Sibling"),
                            ("R", "Relative"),
                            ("G", "Legal Guardian"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "parent_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="register.parentaccount",
                        to_field="parent_id",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register.studentdetail",
                        to_field="student_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("middle_name", models.CharField(max_length=80, null=True)),
                ("last_name", models.CharField(max_length=80)),
                (
                    "suffix",
                    models.CharField(
                        choices=[
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("II", "The second"),
                            ("III", "The third"),
                            ("IV", "The fourth"),
                            ("V", "The fifth"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("birthday", models.DateField()),
                ("address", models.CharField(max_length=255)),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must follow the format '+99999999' between 8-15 digits long.",
                                regex="^\\+?\\1?\\d{8,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("T", "Teacher"), ("S", "Staff"), ("D", "Dean")],
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("R", "Regular"),
                            ("P", "Probationary"),
                            ("S", "Suspended"),
                            ("T", "Terminated"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "employee_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="register.employeeaccount",
                        to_field="employee_id",
                    ),
                ),
            ],
        ),
    ]
