# Generated by Django 4.2.6 on 2024-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allaccount',
            name='username',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
