# Generated by Django 4.2.6 on 2024-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='scholar_type',
            field=models.CharField(choices=[('N', 'Not a scholar'), ('H', 'Half scholarship'), ('F', 'Full scholarship')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='status',
            field=models.CharField(choices=[('N', 'New account, not yet activated'), ('A', 'Active'), ('E', 'Expelled'), ('S', 'Suspended'), ('D', 'Dropped out'), ('G', 'Graduated'), ('X', 'Did not enroll this year')], default='N', max_length=1),
        ),
    ]
