# Generated by Django 4.2.6 on 2024-11-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationkey',
            name='year_level',
            field=models.CharField(choices=[('EMS1', 'Elementary School 1'), ('EMS2', 'Elementary School 2'), ('EMS3', 'Elementary School 3'), ('EMS4', 'Elementary School 4'), ('EMS5', 'Elementary School 5'), ('EMS6', 'Elementary School 6'), ('MDS1', 'Middle School 1'), ('MDS2', 'Middle School 2'), ('MDS3', 'Middle School 3'), ('MDS4', 'Middle School 4'), ('SHS1', 'High School 1'), ('SHS2', 'High School 2'), ('SHS3', 'High School 3'), ('SHS4', 'High School 4'), ('COL1', 'College Level 1'), ('COL2', 'College Level 2'), ('COL3', 'College Level 3'), ('COL4', 'College Level 4'), ('COL5', 'College Level 5'), ('LAW1', 'Law 1'), ('LAW2', 'Law 2'), ('LAW3', 'Law 3'), ('LAW4', 'Law 4'), ('MST1', 'Masters 1'), ('MST2', 'Masters 2'), ('MST3', 'Masters 3'), ('PHD1', 'Doctorate 1'), ('PHD2', 'Doctorate 2'), ('PHD3', 'Doctorate 3'), ('PHD4', 'Doctorate 4'), ('PHD5', 'Doctorate 5'), ('PHD6', 'Doctorate 6'), ('PHD7', 'Doctorate 7'), ('REGS', 'Regular Staff'), ('PHDT', 'PHD Teacher'), ('MSTT', 'Masters Teacher'), ('LAWT', 'Law Teacher'), ('COLT', 'College Teacher'), ('SHST', 'High School Teacher'), ('MDST', 'Middle School Teacher'), ('EMST', 'Elementary School Teacher'), ('F', 'Father'), ('M', 'Mother'), ('S', 'Sibling'), ('R', 'Relative'), ('G', 'Legal Guardian')]),
        ),
    ]
