# Generated by Django 4.2.6 on 2024-06-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allaccount',
            name='allow_login',
        ),
    ]
