# Generated by Django 4.2.6 on 2024-03-24 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_studentdetail_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='phone',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must follow the format '+99999999' between 8-15 digits long.", regex='^\\+?\\1?\\d{8,15}$')]),
        ),
    ]
