# Generated by Django 4.2.6 on 2024-04-23 08:00

import django.core.validators
from django.db import migrations, models
import register.custom


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_employeedetail_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='birthday',
            field=models.DateField(validators=[register.custom.staff_parent_age_validator]),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must follow the format '+99999999' between 8-15 digits long.", regex='^\\+?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='parentdetail',
            name='birthday',
            field=models.DateField(validators=[register.custom.staff_parent_age_validator]),
        ),
        migrations.AlterField(
            model_name='parentdetail',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must follow the format '+99999999' between 8-15 digits long.", regex='^\\+?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='birthday',
            field=models.DateField(validators=[register.custom.student_age_validator]),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='phone',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must follow the format '+99999999' between 8-15 digits long.", regex='^\\+?\\d{8,15}$')]),
        ),
    ]
