services:
  enrollment:
    env_file:
      - ./allen_academy_enrollment/.env.dev
    build: ./allen_academy_enrollment
    depends_on:
      - login
    ports:
      - "8800:8800"
    volumes:
      - ./allen_academy_enrollment:/usr/src/app
    networks:
      - backend

  login:
    env_file:
      - ./allen_academy_login/.env.dev
    build: ./allen_academy_login
    depends_on:
      - register
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./allen_academy_login:/usr/src/app
    networks:
      - backend

  register:
    env_file:
      - ./allen_academy_register/.env.dev
    build: ./allen_academy_register
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./allen_academy_register:/usr/src/app
    networks:
      - backend
    
  schadmin:
    env_file:
      - ./allen_academy_school_administration/.env.dev
    build: ./allen_academy_school_administration
    depends_on:
      - login
    ports:
      - "8880:8880"
    volumes:
      - ./allen_academy_school_administration:/usr/src/app
    networks:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
