version: '3.9'
services:
  api_gateway:
    build: ./api_gateway
    depends_on:
      - db
    volumes:
      - ./api_gateway:/usr/src/app
    networks:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend: