version: '3.9'
services:
  register:
    env_file:
      - ./allen_academy_register/.env.dev
    build: ./allen_academy_register
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend: