version: '3.9'
services:
  register:
    env_file:
      - ./allen_academy_register/.env.dev
    build: ./allen_academy_register
    depends_on:
      - api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./allen_academy_register:/usr/src/app
    networks:
      - backend
    
  api_gateway:
    build: ./api_gateway
    depends_on:
      - db
    volumes:
      - ./api_gateway:/usr/src/app
    networks:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend: