# FROM node:latest as build

# ENV DockerHOME=/usr/src/app
# RUN mkdir -p $DockerHOME
# COPY . $DockerHOME
# WORKDIR $DockerHOME

# COPY package*.json ./
# RUN npm install vite

# COPY . .

# FROM nginx:alpine

# COPY --from=build /usr/src/app /usr/share/nginx/html

# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
