# Generated by Django 4.2.6 on 2024-06-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('edu_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectblock',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.employeedetail'),
        ),
        migrations.AddField(
            model_name='subjectblock',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_admin.coursesubject'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depts_created', to='register.employeedetail'),
        ),
        migrations.AddField(
            model_name='department',
            name='dept_head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dept_headed', to='register.employeedetail'),
        ),
        migrations.AddField(
            model_name='department',
            name='dept_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edu_admin.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depts_updated', to='register.employeedetail'),
        ),
        migrations.AddField(
            model_name='coursesubject',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_admin.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_admin.department'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu_admin.subjectblock', to_field='block_id'),
        ),
    ]
